site_name: Weihergames
site_author: Daniel Thiel, Dominik Hoffendahl

theme:
  name: material
pages:
  - Home: 'index.md'
  - Regelwerk:
      - Grundregeln: 'basics/grundregeln.md'
      - Season Regeln: 'seasons/weiherlympics.md'
      - Field Of Plays: 'basics/field_of_plays.md'
  - Spiele:
      - Unfertige Regeln (TODO): 'games/todo.md'
      - Hit The Line: 'games/hit_the_line.md'
      - Jumpergame: 'games/jumpergame.md'
  - ğŸ† Upcoming:
      - Funfix Open 2021: 'seasons/2021_funfix_open.md'
  - ğŸ† Ongoing:
      - Weiherlympics 2018: 'seasons/2018_weiherlympics.md'
  - ğŸ† Completed:
      - Winterspiele 2012: 'seasons/2012_winterspiele.md'
      - Sommerspiele 2012: 'seasons/2012_sommerspiele.md'
  - Teilnehmer:
      - Ãœbersicht: 'users/overview.md'
      - Doompy: 'users/doompy.md'
      - Mazl: 'users/mazl.md'
      - Theel: 'users/theel.md'
  - Rangliste: 'rangliste.md'
plugins:
  - markdownmermaid
extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js
  - js/iframeUtils.js
